### ISSUE TITLE
Missing file error 

### ISSUE THREAD

**Issue by amunzur** [salzmanlab/SICILIAN#1]
Dear Sicilian team, 

Thank you for developing this great tool! 

I ran into an issue when generating the annotator pickle files. I added the error message below: 

```
/oak/stanford/groups/horence/Roozbeh/single_cell_project/scripts/STAR_wrapper/annotators/hg38.pkl
sys:1: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
Traceback (most recent call last):
  File "create_annotator.py", line 96, in <module>
    main()
  File "create_annotator.py", line 75, in main
    pickle.dump(exon_bounds, open("{}annotators/{}_exon_bounds.pkl".format(wrapper_path, args.assembly), "wb"))
FileNotFoundError: [Errno 2] No such file or directory: '/oak/stanford/groups/horence/Roozbeh/single_cell_project/scripts/STAR_wrapper/annotators/hg38_exon_bounds.pkl'
```

I took a look at the `create_annotator.py`, and I noticed that you have this path written down in the `main` function: 

```
  wrapper_path = "/oak/stanford/groups/horence/Roozbeh/single_cell_project/scripts/STAR_wrapper/"
```
`wrapper_path` is mentioned a couple of times in the function. I don't have this path anywhere in my environment through. Was this path supposed to be generated somehow when I installed the package? 

Many thanks for all your help!

**Comment by carbycrab** [comment]
Hello Sicilian Team,

I am also getting this error. Thanks so much for the help!

**Comment by ZijieJin** [comment]
Hello, Sicilian Team,

I also found this error. It seems that you may modify the path in the create_annotator.py to fix this error

**Comment by amunzur** [comment]
Any updates on the issue?

**Comment by jkniehaus** [comment]
Hello,
I am also experiencing this issue. Tried altering the path, but still without any luck. Any ideas?

**Comment by salzmanlab-admin** [comment]
Sorry for the delay on this. The create_annotator.py script has now been updated and the issue with the the path has now been resolved.
