### ISSUE TITLE
Input parameters for SICILIAN

### ISSUE THREAD

**Issue by tjhwangxiong** [salzmanlab/SICILIAN#11]
```bc_pattern```:  this parameter is needed only for 10x data and determines the barcode/UMI pattern in R1. For V3 chemistry in which UMI has 12 bps, ```bc_pattern```  should be set to ```"C"*16 + "N"*12```  and for 10x data based on V2 chemistry it should be set to ```"C"*16 + "N"*12```. ```bc_pattern``` is needed for ```UMI_tools``` steps before STAR alignment on input 10x data.

The  ```bc_pattern``` is the same for V2 and V3 in https://github.com/salzmanlab/SICILIAN#annotator-and-index-files-needed-for-running-sicilian section: Input parameters for SICILIAN

Is it should be:
```bc_pattern```:  this parameter is needed only for 10x data and determines the barcode/UMI pattern in R1. For V3 chemistry in which UMI has 12 bps, ```bc_pattern```  should be set to ```"C"*16 + "N"*12```  and for 10x data based on V2 chemistry it should be set to ```"C"*16 + "N"*10```. ```bc_pattern``` is needed for ```UMI_tools``` steps before STAR alignment on input 10x data. ?

As the UMI of V2 was 10 bp.

**Comment by roozbehdn** [comment]
Yes, you are right, the UMI is 10bp in V2. Thanks for finding this, we corrected the readme file.
