### ISSUE TITLE
FASTQ Formats compatible with SICILIAN 

### ISSUE THREAD

**Issue by malbahrani** [salzmanlab/SICILIAN#13]
Hi,

What are the [FASTQ file formats](http://www.arrayserver.com/wiki/index.php?title=Preprocess_of_SingleCell_RNA-Seq_Data) compatible with SICILIAN? Does it specifically support the following format?

http://www.arrayserver.com/wiki/images/5/5b/SC_preprocess4.png

Thanks,

**Comment by roozbehdn** [comment]
Currently, the default preprocessing is based on 10x sequencing where R1 contains (barcode + UMI) and the number of bases for barcode and UMI are determined by `bc_pattern` parameter. R2 contains the biological read for the cDNA molecule. Your attached format is a bit different from 10x format as despite 10x (where only R2 contains biological reads) both R1 and R2 in your format contain biological reads.
