### ISSUE TITLE
Enhancement request: cutpointr should be listed under the 'Software requirements' section of README.md

### ISSUE THREAD

**Issue by fomightez** [salzmanlab/SICILIAN#24]
`GLM_script_light.R` installs several R libraries if they aren't present, and `cutpointr` is one of them.  
However, that one is not listed in the list of R libraries under the 'Software requirements' section of README.md.

**Comment by roozbehdn** [comment]
Thanks for your suggestion, we have now added `cutpointr` under Software requirements section
