### ISSUE TITLE
Further Documentation of the SICILIAN Output

### ISSUE THREAD

**Issue by apdavid** [salzmanlab/SICILIAN#5]
I have completed the the SICILIAN pipeline on our dataset and we were hoping to get some clarification on the output and how to determine the true junction calls:

there are a few variables in particular that looked helpful, namely: `both_ann`, `postprocess_passed`, `passed_tot` and `called`

Also looking for guidance on next steps for using the SICILIAN pipeline produced data to doing further differentially spliced analysis.

Thank you, your help is greatly appreciated.

**Comment by roozbehdn** [comment]
Hello, sorry for the late reply. I did not get notification for your message. `both_ann` column determines whether both exon boundaries are annotated in the splice junction. You can disregard the two passed columns as they are used for internal sicilian analysis. The final column for calling junctions is `called`. You can use it for filtering junctions and it is the column that SpliZ uses for finding true positive junctions if you input sicilian files to splize.
