### ISSUE TITLE
A brief test to start up?

### ISSUE THREAD

**Issue by ryao-mdanderson** [salzmanlab/SICILIAN#7]
Dear SICILIAN development team: @roozbehdn 
  Thank you for sharing this tool. I am trying to install the tool on our institution HPC cluster, we use LSF scheduler instead. I have been set up the software requirements (python and R packages and umi_tools). Now, I would like to have some helps to make a test:
 Download data. I will the approach to down ready-to-user and annotator files. The data are hosted in drive.google.com. I am not able to access. should I have to have a google account?
Is there minimal requested files that can be used as a start up test, probably in the github repository?

Thank you very much.
Rong

**Comment by MEFarhadieh** [comment]
Dear ryao-mdanderson, I used gdown for downloading those files. 
you can install gdown by `pip install gdown` 
and then `gdown https://drive.google.com/uc?id=<file_id>`
For example, for Human on this repository you can use `gdown https://drive.google.com/uc?id=1cGfn7MZbGewBJp6ZGGW_IOW3nWEAHOPz&export=download`

**Comment by ryao-mdanderson** [comment]
@katze99 Thank you. Your gdown command and example work for me.
