### ISSUE TITLE
dimain file

### ISSUE THREAD

**Issue by kayla-xu** [salzmanlab/SICILIAN#9]
Where is the domain file in UCSC? I can't find it, please

**Comment by roozbehdn** [comment]
The domain file provides the location of the protein domains in the genome and is used by sicilian to annotate the protein domain arrangement in the resulting splice junctions. It is an optional file though and no problem if it is not provided as an input file to sicilian. For mouse and human you can download it using the links provided here (`https://github.com/salzmanlab/SICILIAN#annotator-and-index-files-needed-for-running-sicilian`)
you can also download it directly from ucsc from: `https://hgdownload.cse.ucsc.edu/goldenPath/mm10/database/` (you need to replace mm10 with your genome name of desire) and then look for a file with name `ucscGenePfam.txt`.
